// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/22/2024, 8:42:12 PM
const configMerger = require("/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/plugins/**/*.{js,ts,mjs}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/composables/**/*.{js,ts,mjs}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/utils/**/*.{js,ts,mjs}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/miroslavandreas/Sites/localhost/sa-nuxt-bolt/app.config.{js,ts,mjs}"] } }));

module.exports = config
